//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWS SNS device topic endpoint wasn&apos;t enabled..
        /// </summary>
        public static string AwsEndpointIsNotEnabled {
            get {
                return ResourceManager.GetString("AwsEndpointIsNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email address..
        /// </summary>
        public static string EmailIsNotValid {
            get {
                return ResourceManager.GetString("EmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email wasn&apos;t activated..
        /// </summary>
        public static string EmailIsNotValidated {
            get {
                return ResourceManager.GetString("EmailIsNotValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation is unavailable for external users..
        /// </summary>
        public static string NotForExternal {
            get {
                return ResourceManager.GetString("NotForExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os type is not supported..
        /// </summary>
        public static string OsTypeInvalid {
            get {
                return ResourceManager.GetString("OsTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect..
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied.
        /// </summary>
        public static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password was not requested..
        /// </summary>
        public static string ResetPasswordNotRequested {
            get {
                return ResourceManager.GetString("ResetPasswordNotRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password request has expired..
        /// </summary>
        public static string ResetPasswordRequestExpired {
            get {
                return ResourceManager.GetString("ResetPasswordRequestExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but you&apos;re blocked by admin..
        /// </summary>
        public static string UserBlocked {
            get {
                return ResourceManager.GetString("UserBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User device id not found..
        /// </summary>
        public static string UserDeviceIdNotFound {
            get {
                return ResourceManager.GetString("UserDeviceIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User device token not found..
        /// </summary>
        public static string UserDeviceNotFound {
            get {
                return ResourceManager.GetString("UserDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid activation code..
        /// </summary>
        public static string UserEntityCodeIsNotValidate {
            get {
                return ResourceManager.GetString("UserEntityCodeIsNotValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we already have user with this E-Mail address..
        /// </summary>
        public static string UserExist {
            get {
                return ResourceManager.GetString("UserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t fetch data from API about user..
        /// </summary>
        public static string UserFetchApi {
            get {
                return ResourceManager.GetString("UserFetchApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find user with specific email..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find user with specific id  {0}..
        /// </summary>
        public static string UserSpecificId {
            get {
                return ResourceManager.GetString("UserSpecificId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find specific user..
        /// </summary>
        public static string UserSpecificNotFound {
            get {
                return ResourceManager.GetString("UserSpecificNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User auth token not found..
        /// </summary>
        public static string UserTokenNotFound {
            get {
                return ResourceManager.GetString("UserTokenNotFound", resourceCulture);
            }
        }
    }
}
