//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EmailTemplates", typeof(EmailTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;body&gt;
        ///&lt;p&gt;Dear {0},&lt;/p&gt;
        ///&lt;p&gt;&lt;/p&gt;
        ///&lt;p&gt;You have changed password for your account at Web App&lt;/p&gt;
        ///&lt;p&gt;&lt;/p&gt;
        ///&lt;p&gt;Your new password is: &lt;b&gt;{1}&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;/p&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string ChangePasswordBody {
            get {
                return ResourceManager.GetString("ChangePasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePasswordSubject {
            get {
                return ResourceManager.GetString("ChangePasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;body&gt;
        ///&lt;p&gt;Dear {0},&lt;/p&gt;
        ///&lt;p&gt;&lt;/p&gt;
        ///&lt;p&gt;You have requested to have your password reset for your account at Web App&lt;/p&gt;
        ///&lt;p&gt;&lt;/p&gt;
        ///&lt;p&gt;We generate new password for you: &lt;b&gt;{1}&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;/p&gt;
        ///&lt;p&gt;If you received this email in error, you can safely ignore this email.&lt;/p&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string ForgotPasswordBody {
            get {
                return ResourceManager.GetString("ForgotPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0&quot;&gt;
        ///	&lt;title&gt;Your password has been…&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;color: #000000; font-family: Arial; font-size: 18px; margin: 0;&quot;&gt;
        ///&lt;main&gt;
        ///    &lt;div style=&quot;padding: 12px;&quot;&gt;
        ///        &lt;p style=&quot;margin: 20px 0;&quot;&gt;Hi there, &lt;/p&gt;
        ///        &lt;p style=&quot;margin: 20px 0;&quot;&gt;We received a request to reset the password for your accou [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ForgotPasswordLinkBody {
            get {
                return ResourceManager.GetString("ForgotPasswordLinkBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Password.
        /// </summary>
        public static string ForgotPasswordSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;body&gt;
        ///&lt;p&gt;Congratulation {0},&lt;/p&gt;
        ///&lt;p&gt;&lt;/p&gt;
        ///&lt;p&gt;Now you are admin!&lt;/p&gt;
        ///&lt;p&gt;&lt;/p&gt;
        ///&lt;p&gt;We generate new password for you. You can change it if you want in settings. &lt;/p&gt;
        ///&lt;p&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;b&gt;{1}&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;/p&gt;
        ///&lt;p&gt;If you received this email in error, you can safely ignore this email. &lt;/p&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string NewAdminRegisterBody {
            get {
                return ResourceManager.GetString("NewAdminRegisterBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are admin.
        /// </summary>
        public static string NewAdminRegisterSubject {
            get {
                return ResourceManager.GetString("NewAdminRegisterSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;body&gt;
        ///&lt;p&gt;Dear  {0},&lt;/p&gt;
        ///&lt;p&gt;&lt;/p&gt;
        ///&lt;p&gt;We generate new verification code for you.&lt;/p&gt;
        ///&lt;p&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;b&gt;{1}&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;/p&gt;
        ///&lt;p&gt;If you received this email in error, you can safely ignore this email. &lt;/p&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string VerificationCodeBody {
            get {
                return ResourceManager.GetString("VerificationCodeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string VerificationCodeSubject {
            get {
                return ResourceManager.GetString("VerificationCodeSubject", resourceCulture);
            }
        }
    }
}
